# -*- coding: utf-8 -*-
"""LR_2_task_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12n9clMP8obaYSh_DsSvK_818FJnVDHDs
"""

# ==============================
# ІМПОРТИ
# ==============================
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

# ==============================
# ЗАВАНТАЖЕННЯ ДАНИХ
# ==============================
input_file = 'income_data.txt'

X = []
count_class1 = 0
count_class2 = 0
max_datapoints = 3000

with open(input_file, 'r') as f:
    for line in f:
        if count_class1 >= max_datapoints and count_class2 >= max_datapoints:
            break

        if '?' in line:
            continue

        data = line.strip().split(', ')

        if data[-1] == '<=50K' and count_class1 < max_datapoints:
            X.append(data)
            count_class1 += 1

        elif data[-1] == '>50K' and count_class2 < max_datapoints:
            X.append(data)
            count_class2 += 1

X = np.array(X)

# ==============================
# КОДУВАННЯ
# ==============================
label_encoders = []
X_encoded = np.empty(X.shape)

for i in range(X.shape[1]):
    if X[0, i].isdigit():
        X_encoded[:, i] = X[:, i]
    else:
        encoder = preprocessing.LabelEncoder()
        X_encoded[:, i] = encoder.fit_transform(X[:, i])
        label_encoders.append((i, encoder))

X_data = X_encoded[:, :-1].astype(int)
y_data = X_encoded[:, -1].astype(int)

# ==============================
# РОЗБИТТЯ ДАНИХ
# ==============================
X_train, X_test, y_train, y_test = train_test_split(
    X_data, y_data, test_size=0.2, random_state=1
)

# ==============================
# МАСШТАБУВАННЯ (ВАЖЛИВО!)
# ==============================
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ==============================
# МОДЕЛІ
# ==============================
models = []
models.append(('LR', LogisticRegression(max_iter=2000, solver='liblinear')))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))

# ==============================
# ОЦІНКА
# ==============================
results = []
names = []

print("\nРезультати алгоритмів:")

for name, model in models:
    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=1)
    cv_results = cross_val_score(model, X_train, y_train, cv=kfold, scoring='accuracy')

    results.append(cv_results)
    names.append(name)

    print(f"{name}: {cv_results.mean():.4f}")

# ==============================
# ГРАФІК
# ==============================
plt.boxplot(results, labels=names)
plt.title("Порівняння алгоритмів (income_data)")
plt.show()

# ==============================
# ТЕСТ НА КРАЩІЙ МОДЕЛІ (SVM)
# ==============================
model = SVC()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\nОцінка SVM на тестових даних:")
print("Accuracy:", round(accuracy_score(y_test, y_pred), 4))