# -*- coding: utf-8 -*-
"""LR_2_task_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASoVlSixdtq3S6zM9XfkzDIKVXbA6aRX
"""

# ==============================
# ІМПОРТИ
# ==============================
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import RidgeClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix

# ==============================
# ЗАВАНТАЖЕННЯ IRIS
# ==============================
iris = load_iris()

X = iris.data
y = iris.target

# ==============================
# РОЗБИТТЯ ДАНИХ
# ==============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0
)

# ==============================
# СТВОРЕННЯ ТА НАВЧАННЯ МОДЕЛІ
# ==============================
clf = RidgeClassifier(tol=1e-2, solver="sag")
clf.fit(X_train, y_train)

# ==============================
# ПРОГНОЗ
# ==============================
y_pred = clf.predict(X_test)

# ==============================
# ПОКАЗНИКИ ЯКОСТІ
# ==============================
print("Accuracy:", np.round(metrics.accuracy_score(y_test, y_pred), 4))
print("Precision:", np.round(metrics.precision_score(y_test, y_pred, average='weighted'), 4))
print("Recall:", np.round(metrics.recall_score(y_test, y_pred, average='weighted'), 4))
print("F1 Score:", np.round(metrics.f1_score(y_test, y_pred, average='weighted'), 4))
print("Cohen Kappa Score:", np.round(metrics.cohen_kappa_score(y_test, y_pred), 4))
print("Matthews Corrcoef:", np.round(metrics.matthews_corrcoef(y_test, y_pred), 4))

print("\nClassification Report:\n")
print(metrics.classification_report(y_test, y_pred, target_names=iris.target_names))

# ==============================
# МАТРИЦЯ ПОМИЛОК
# ==============================
mat = confusion_matrix(y_test, y_pred)

sns.heatmap(
    mat.T,
    square=True,
    annot=True,
    fmt='d',
    cbar=False,
    xticklabels=iris.target_names,
    yticklabels=iris.target_names
)

plt.xlabel("True label")
plt.ylabel("Predicted label")
plt.title("Confusion Matrix — Ridge Classifier")

plt.savefig("Confusion.jpg")
plt.show()