# -*- coding: utf-8 -*-
"""LR_2_task_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T27mUn1b3V7S5kgtii01tvUlbVL8DIbT
"""

# ==============================
# ІМПОРТИ
# ==============================
from pandas import read_csv
from pandas.plotting import scatter_matrix
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

import numpy as np

# ==============================
# КРОК 1. ЗАВАНТАЖЕННЯ ДАНИХ
# ==============================
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = read_csv(url, names=names)

print("Розмір датасету:", dataset.shape)
print(dataset.head())

# ==============================
# КРОК 2. ВІЗУАЛІЗАЦІЯ
# ==============================
dataset.plot(kind='box', subplots=True, layout=(2,2))
pyplot.title("Boxplot")
pyplot.show()

dataset.hist()
pyplot.title("Histogram")
pyplot.show()

scatter_matrix(dataset)
pyplot.title("Scatter Matrix")
pyplot.show()

# ==============================
# КРОК 3. РОЗДІЛЕННЯ ДАНИХ
# ==============================
array = dataset.values
X = array[:, 0:4]
y = array[:, 4]

X_train, X_validation, Y_train, Y_validation = train_test_split(
    X, y, test_size=0.20, random_state=1
)

# ==============================
# КРОК 4. ПОРІВНЯННЯ АЛГОРИТМІВ
# ==============================
models = []
models.append(('LR', LogisticRegression(max_iter=200)))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC(gamma='auto')))

results = []
names_models = []

print("\nРезультати моделей:")

for name, model in models:
    kfold = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
    cv_results = cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
    results.append(cv_results)
    names_models.append(name)
    print(f"{name}: {cv_results.mean():.4f} ({cv_results.std():.4f})")

# ==============================
# ГРАФІК ПОРІВНЯННЯ
# ==============================
pyplot.boxplot(results, labels=names_models)
pyplot.title('Порівняння алгоритмів')
pyplot.show()

# ==============================
# КРОК 6. НАВЧАННЯ КРАЩОЇ МОДЕЛІ
# ==============================
model = SVC(gamma='auto')
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)

# ==============================
# КРОК 7. ОЦІНКА
# ==============================
print("\nОцінка моделі:")
print("Accuracy:", accuracy_score(Y_validation, predictions))
print("\nМатриця помилок:")
print(confusion_matrix(Y_validation, predictions))
print("\nЗвіт класифікації:")
print(classification_report(Y_validation, predictions))

# ==============================
# КРОК 8. ПРОГНОЗ
# ==============================
X_new = np.array([[5, 2.9, 1, 0.2]])

prediction = model.predict(X_new)
print("\nПрогноз для нової квітки:", prediction)