# -*- coding: utf-8 -*-
"""LR_3_task_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kth8e3jlXQCotOEEmqi2FH5RyOpD49Zp
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Генерація даних за варіантом 6
m = 100
X = np.linspace(-3, 3, m).reshape(-1, 1)
y = 2 * np.sin(X) + np.random.uniform(-0.6, 0.6, (m, 1))

# Лінійна регресія
lin_reg = LinearRegression()
lin_reg.fit(X, y)

# Поліноміальна регресія
poly = PolynomialFeatures(degree=5, include_bias=False)
X_poly = poly.fit_transform(X)

poly_reg = LinearRegression()
poly_reg.fit(X_poly, y)

# Створення плавної лінії для прогнозу
X_new = np.linspace(-3, 3, 200).reshape(-1, 1)
X_new_poly = poly.transform(X_new)
y_new_poly = poly_reg.predict(X_new_poly)

# Побудова графіка
plt.scatter(X, y, color='blue', s=15)
plt.plot(X_new, y_new_poly, color='red', linewidth=2, label='Прогнози')
plt.xlabel('X')
plt.ylabel('y')
plt.legend()
plt.show()

# Виведення моделей
print("Модель варіанту:")
print("y = 2 * sin(x) + шум")

print("\nЛінійна модель:")
print("y =", round(lin_reg.coef_[0][0], 3), "* x +", round(lin_reg.intercept_[0], 3))

print("\nПоліноміальна модель:")
print("intercept =", round(poly_reg.intercept_[0], 3))
print("coefficients =", poly_reg.coef_)