# -*- coding: utf-8 -*-
"""LR_3_task_6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kth8e3jlXQCotOEEmqi2FH5RyOpD49Zp
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

# Дані з попереднього завдання (варіант 6)
m = 100
X = np.linspace(-3, 3, m).reshape(-1, 1)
y = 2 * np.sin(X) + np.random.uniform(-0.6, 0.6, (m, 1))

# Функція для побудови кривих навчання
def plot_learning_curves(model, X, y):
    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)
    train_errors, val_errors = [], []

    for m in range(1, len(X_train)):
        model.fit(X_train[:m], y_train[:m])
        y_train_pred = model.predict(X_train[:m])
        y_val_pred = model.predict(X_val)

        train_errors.append(mean_squared_error(y_train[:m], y_train_pred))
        val_errors.append(mean_squared_error(y_val, y_val_pred))

    plt.plot(np.sqrt(train_errors), "r-", linewidth=2, label="train")
    plt.plot(np.sqrt(val_errors), "b-", linewidth=2, label="val")
    plt.xlabel("Кількість навчальних прикладів")
    plt.ylabel("RMSE")
    plt.legend()
    plt.show()

# 1. Лінійна регресія
lin_reg = LinearRegression()
plot_learning_curves(lin_reg, X, y)

# 2. Поліноміальна регресія (ступінь 10)
poly10 = Pipeline([
    ("poly_features", PolynomialFeatures(degree=10, include_bias=False)),
    ("lin_reg", LinearRegression())
])
plot_learning_curves(poly10, X, y)

# 3. Поліноміальна регресія (ступінь 2)
poly2 = Pipeline([
    ("poly_features", PolynomialFeatures(degree=2, include_bias=False)),
    ("lin_reg", LinearRegression())
])
plot_learning_curves(poly2, X, y)