# -*- coding: utf-8 -*-
"""LR_3_task_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kth8e3jlXQCotOEEmqi2FH5RyOpD49Zp
"""

import numpy as np
from sklearn import linear_model
import sklearn.metrics as sm
from sklearn.preprocessing import PolynomialFeatures

# Завантаження даних
input_file = 'data_multivar_regr.txt'
data = np.loadtxt(input_file, delimiter=',')

# Розділення на X та y
X, y = data[:, :-1], data[:, -1]

# Розбивка
num_training = int(0.8 * len(X))
X_train, y_train = X[:num_training], y[:num_training]
X_test, y_test = X[num_training:], y[num_training:]

# Лінійна регресія
linear_regressor = linear_model.LinearRegression()
linear_regressor.fit(X_train, y_train)

y_test_pred = linear_regressor.predict(X_test)

print("Linear regression:")
print("MAE =", round(sm.mean_absolute_error(y_test, y_test_pred), 2))
print("MSE =", round(sm.mean_squared_error(y_test, y_test_pred), 2))
print("R2 =", round(sm.r2_score(y_test, y_test_pred), 2))

# Поліноміальна регресія
polynomial = PolynomialFeatures(degree=10)
X_train_poly = polynomial.fit_transform(X_train)

poly_model = linear_model.LinearRegression()
poly_model.fit(X_train_poly, y_train)

# тест
X_test_poly = polynomial.transform(X_test)
y_test_pred_poly = poly_model.predict(X_test_poly)

print("\nPolynomial regression:")
print("MAE =", round(sm.mean_absolute_error(y_test, y_test_pred_poly), 2))
print("MSE =", round(sm.mean_squared_error(y_test, y_test_pred_poly), 2))
print("R2 =", round(sm.r2_score(y_test, y_test_pred_poly), 2))

# прогноз для точки
datapoint = [[7.75, 6.35, 5.56]]

print("\nLinear prediction:", linear_regressor.predict(datapoint))

datapoint_poly = polynomial.transform(datapoint)
print("Polynomial prediction:", poly_model.predict(datapoint_poly))