# -*- coding: utf-8 -*-
"""LR_3_task_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kth8e3jlXQCotOEEmqi2FH5RyOpD49Zp
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Генерація даних (варіант 6)
m = 100
X = np.linspace(-3, 3, m).reshape(-1, 1)
y = 2 * np.sin(X) + np.random.uniform(-0.6, 0.6, (m, 1))

# Лінійна регресія
lin_reg = LinearRegression()
lin_reg.fit(X, y)
y_lin = lin_reg.predict(X)

# Поліноміальна регресія (ступінь 2)
poly = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(X)

poly_reg = LinearRegression()
poly_reg.fit(X_poly, y)
y_poly = poly_reg.predict(X_poly)

# Графік
plt.scatter(X, y, color='blue', label='Дані')
plt.plot(X, y_lin, color='red', label='Лінійна регресія')
plt.plot(X, y_poly, color='green', label='Поліноміальна регресія')
plt.legend()
plt.show()

# Коефіцієнти
print("Linear coefficients:", lin_reg.coef_, lin_reg.intercept_)
print("Polynomial coefficients:", poly_reg.coef_, poly_reg.intercept_)