# -*- coding: utf-8 -*-
"""LR_3_task_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kth8e3jlXQCotOEEmqi2FH5RyOpD49Zp
"""

import numpy as np
from sklearn import linear_model
import sklearn.metrics as sm
import matplotlib.pyplot as plt

# Вхідний файл (твій варіант 1)
input_file = 'data_regr_1.txt'

# Завантаження даних
data = np.loadtxt(input_file, delimiter=',')

# Розділення на X та y
X, y = data[:, :-1], data[:, -1]

# Розбивка даних
num_training = int(0.8 * len(X))

X_train, y_train = X[:num_training], y[:num_training]
X_test, y_test = X[num_training:], y[num_training:]

# Створення моделі
regressor = linear_model.LinearRegression()
regressor.fit(X_train, y_train)

# Прогноз
y_test_pred = regressor.predict(X_test)

# Графік
plt.scatter(X_test, y_test, color='blue', label='Реальні дані')
plt.plot(X_test, y_test_pred, color='red', linewidth=3, label='Прогноз')
plt.xlabel('X')
plt.ylabel('y')
plt.title('Регресія (варіант 1)')
plt.legend()
plt.show()

# Метрики
print("Mean absolute error =", round(sm.mean_absolute_error(y_test, y_test_pred), 2))
print("Mean squared error =", round(sm.mean_squared_error(y_test, y_test_pred), 2))
print("Median absolute error =", round(sm.median_absolute_error(y_test, y_test_pred), 2))
print("Explained variance score =", round(sm.explained_variance_score(y_test, y_test_pred), 2))
print("R2 score =", round(sm.r2_score(y_test, y_test_pred), 2))