# -*- coding: utf-8 -*-
"""LR_4_task_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuhjGInv8hs9X3L8yUPJXnBEtiqy6YTg
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans

# Завантаження набору даних Iris
# Тут є 150 об'єктів і 4 ознаки
iris = load_iris()
X = iris.data  # ознаки (довжина/ширина)
y = iris.target  # справжні класи (не використовуються для навчання)

# Створення моделі KMeans
# n_clusters=3 — бо в Iris 3 види квітів
kmeans = KMeans(n_clusters=3, random_state=0)

# Навчання моделі
kmeans.fit(X)

# Прогноз кластерів
y_kmeans = kmeans.predict(X)

# Візуалізація (беремо тільки 2 ознаки для графіка)
plt.figure()
plt.scatter(X[:, 0], X[:, 1], c=y_kmeans, s=50, cmap='viridis')

# Центри кластерів
centers = kmeans.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1],
            c='black', s=200, alpha=0.5)

plt.title("Кластери Iris (K-means)")
plt.xlabel("Довжина чашолистка")
plt.ylabel("Ширина чашолистка")
plt.show()