# -*- coding: utf-8 -*-
"""LR_4_task_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuhjGInv8hs9X3L8yUPJXnBEtiqy6YTg
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Завантаження вхідних даних
# У файлі кожен рядок — це точка (x, y)
X = np.loadtxt('data_clustering.txt', delimiter=',')

# Побудова графіка вхідних даних
# Просто дивимось як виглядають точки
plt.figure()
plt.scatter(X[:, 0], X[:, 1], marker='o', facecolors='none', edgecolors='black')
plt.title("Вхідні дані")
plt.xticks([])
plt.yticks([])
plt.show()

# Кількість кластерів (зазвичай видно ≈5)
num_clusters = 5

# Створення моделі KMeans
# init='k-means++' — розумна ініціалізація центрів
# n_init=10 — кількість запусків алгоритму
kmeans = KMeans(init='k-means++', n_clusters=num_clusters, n_init=10)

# Навчання моделі
kmeans.fit(X)

# Побудова сітки для відображення меж
step_size = 0.01

x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1

x_vals, y_vals = np.meshgrid(
    np.arange(x_min, x_max, step_size),
    np.arange(y_min, y_max, step_size)
)

# Прогноз для кожної точки сітки
output = kmeans.predict(np.c_[x_vals.ravel(), y_vals.ravel()])
output = output.reshape(x_vals.shape)

# Малюємо області кластерів
plt.figure()
plt.imshow(output,
           interpolation='nearest',
           extent=(x_vals.min(), x_vals.max(), y_vals.min(), y_vals.max()),
           cmap=plt.cm.Paired,
           aspect='auto',
           origin='lower')

# Малюємо вхідні точки
plt.scatter(X[:, 0], X[:, 1], marker='o', facecolors='none', edgecolors='black', s=80)

# Малюємо центри кластерів
cluster_centers = kmeans.cluster_centers_
plt.scatter(cluster_centers[:, 0], cluster_centers[:, 1],
            marker='o',
            s=200,
            linewidths=3,
            color='black',
            zorder=10)

plt.title("Кластери (K-means)")
plt.xticks([])
plt.yticks([])
plt.show()