# -*- coding: utf-8 -*-
"""LR_4_task_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuhjGInv8hs9X3L8yUPJXnBEtiqy6YTg
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import MeanShift, estimate_bandwidth

# Завантаження даних
# Ті самі дані що в 2.1
X = np.loadtxt('data_clustering.txt', delimiter=',')

# Оцінка ширини вікна (bandwidth)
# Впливає на кількість кластерів
bandwidth = estimate_bandwidth(X, quantile=0.1, n_samples=len(X))

# Створення моделі Mean Shift
meanshift = MeanShift(bandwidth=bandwidth, bin_seeding=True)

# Навчання моделі
meanshift.fit(X)

# Отримання міток кластерів
labels = meanshift.labels_

# Отримання центрів кластерів
cluster_centers = meanshift.cluster_centers_

# Кількість кластерів
num_clusters = len(np.unique(labels))

print("Centers of clusters:\n", cluster_centers)
print("\nNumber of clusters =", num_clusters)

# Візуалізація
plt.figure()

markers = ['o', 's', '^', 'x', '*', 'd']
for i, marker in zip(range(num_clusters), markers):
    plt.scatter(X[labels == i, 0], X[labels == i, 1], marker=marker)

    # центр кластера
    center = cluster_centers[i]
    plt.plot(center[0], center[1], marker='o',
             markerfacecolor='black',
             markeredgecolor='black',
             markersize=12)

plt.title("Кластери (Mean Shift)")
plt.show()