# -*- coding: utf-8 -*-
"""LR_4_task_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuhjGInv8hs9X3L8yUPJXnBEtiqy6YTg
"""

import numpy as np
import yfinance as yf

from sklearn.cluster import AffinityPropagation
from sklearn.preprocessing import StandardScaler

# Список компаній для аналізу
symbols = np.array([
    "AAPL", "MSFT", "GOOG", "AMZN", "META",
    "TSLA", "IBM", "ORCL", "INTC", "NVDA"
])

names = symbols

# Завантаження біржових даних
data = yf.download(
    symbols.tolist(),
    start="2020-01-01",
    end="2023-01-01",
    auto_adjust=False
)

# Беремо ціни відкриття і закриття
opening = data["Open"].values
closing = data["Close"].values

# Обчислюємо різницю між закриттям і відкриттям
quotes_diff = closing - opening

# Замінюємо пропущені значення на 0
quotes_diff = np.nan_to_num(quotes_diff)

# Нормалізуємо дані
X = StandardScaler().fit_transform(quotes_diff.T)

# Створюємо модель Affinity Propagation
# Вона сама визначає кількість кластерів
model = AffinityPropagation(random_state=0)

# Навчаємо модель
model.fit(X)

# Отримуємо мітки кластерів
labels = model.labels_

# Визначаємо кількість кластерів
num_clusters = len(np.unique(labels))
print("Number of clusters:", num_clusters)

# Виводимо компанії по кластерах
for i in range(num_clusters):
    print("\nCluster", i)
    print(", ".join(names[labels == i]))