# -*- coding: utf-8 -*-
"""LR_5_task_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kth8e3jlXQCotOEEmqi2FH5RyOpD49Zp
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Функція для побудови меж класифікатора
# Вона показує, як модель розділяє простір на різні класи
def visualize_classifier(classifier, X, y, title):
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1

    # Створюємо сітку точок для побудови фону класифікації
    xx, yy = np.meshgrid(
        np.arange(x_min, x_max, 0.02),
        np.arange(y_min, y_max, 0.02)
    )

    # Для кожної точки сітки модель прогнозує клас
    Z = classifier.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    # Малюємо області класів
    plt.contourf(xx, yy, Z, alpha=0.3)

    # Малюємо реальні точки даних
    plt.scatter(X[:, 0], X[:, 1], c=y, edgecolors='black', s=40)
    plt.title(title)
    plt.xlabel("X1")
    plt.ylabel("X2")
    plt.show()


# Завантаження даних
# Перші дві колонки — це ознаки, остання колонка — номер класу
input_file = 'data_random_forests.txt'
data = np.loadtxt(input_file, delimiter=',')

X, y = data[:, :-1], data[:, -1]

# Графік вхідних даних
# Тут видно три класи, які частково перекриваються
plt.scatter(X[:, 0], X[:, 1], c=y, edgecolors='black', s=40)
plt.title("Вхідні дані")
plt.xlabel("X1")
plt.ylabel("X2")
plt.show()

# Розбиття даних на навчальну і тестову вибірки
# 75% даних використовується для навчання, 25% — для перевірки
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=5
)

# Загальні параметри для обох моделей
# n_estimators — кількість дерев
# max_depth — максимальна глибина кожного дерева
params = {
    "n_estimators": 100,
    "max_depth": 4,
    "random_state": 0
}

# Створення моделі Random Forest
# Це ансамбль дерев рішень, які разом приймають рішення про клас
rf_classifier = RandomForestClassifier(**params)
rf_classifier.fit(X_train, y_train)

# Прогноз для тестових даних
y_pred_rf = rf_classifier.predict(X_test)

# Виведення метрик якості Random Forest
print("Random Forest:")
print(classification_report(y_test, y_pred_rf))

# Побудова меж класифікатора Random Forest
visualize_classifier(rf_classifier, X_test, y_test, "Random Forest: тестовий набір")


# Створення моделі Extra Trees
# Цей метод схожий на Random Forest, але використовує більше випадковості
erf_classifier = ExtraTreesClassifier(**params)
erf_classifier.fit(X_train, y_train)

# Прогноз для тестових даних
y_pred_erf = erf_classifier.predict(X_test)

# Виведення метрик якості Extra Trees
print("Extra Trees:")
print(classification_report(y_test, y_pred_erf))

# Побудова меж класифікатора Extra Trees
visualize_classifier(erf_classifier, X_test, y_test, "Extra Trees: тестовий набір")


# Тестові точки для перевірки рівня довіри
# Для кожної точки модель визначає клас і ймовірність належності до нього
test_datapoints = np.array([
    [5, 5],
    [3, 6],
    [6, 4],
    [7, 2],
    [4, 4],
    [5, 2]
])

# Виведення рівнів довіри для Random Forest
print("\nConfidence measure for Random Forest:")
for datapoint in test_datapoints:
    probabilities = rf_classifier.predict_proba([datapoint])[0]
    predicted_class = rf_classifier.predict([datapoint])[0]

    print("\nDatapoint:", datapoint)
    print("Predicted class:", int(predicted_class))
    print("Class probabilities:", np.round(probabilities, 3))

# Візуалізація тестових точок для Random Forest
visualize_classifier(
    rf_classifier,
    test_datapoints,
    rf_classifier.predict(test_datapoints),
    "Random Forest: тестові точки"
)


# Виведення рівнів довіри для Extra Trees
print("\nConfidence measure for Extra Trees:")
for datapoint in test_datapoints:
    probabilities = erf_classifier.predict_proba([datapoint])[0]
    predicted_class = erf_classifier.predict([datapoint])[0]

    print("\nDatapoint:", datapoint)
    print("Predicted class:", int(predicted_class))
    print("Class probabilities:", np.round(probabilities, 3))

# Візуалізація тестових точок для Extra Trees
visualize_classifier(
    erf_classifier,
    test_datapoints,
    erf_classifier.predict(test_datapoints),
    "Extra Trees: тестові точки"
)