# -*- coding: utf-8 -*-
"""LR_5_task_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kth8e3jlXQCotOEEmqi2FH5RyOpD49Zp
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Функція для побудови меж класифікатора
# Вона показує, як модель розділяє простір між класами
def visualize_classifier(classifier, X, y, title):
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1

    # Створюємо сітку точок для фону
    xx, yy = np.meshgrid(
        np.arange(x_min, x_max, 0.02),
        np.arange(y_min, y_max, 0.02)
    )

    # Для кожної точки сітки модель прогнозує клас
    Z = classifier.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    # Малюємо області класів
    plt.contourf(xx, yy, Z, alpha=0.3)

    # Малюємо реальні точки
    plt.scatter(X[:, 0], X[:, 1], c=y, edgecolors='black', s=40)
    plt.title(title)
    plt.xlabel("X1")
    plt.ylabel("X2")
    plt.show()


# Завантаження даних
# Перші дві колонки — це ознаки, остання колонка — клас
input_file = 'data_imbalance.txt'
data = np.loadtxt(input_file, delimiter=',')

X, y = data[:, :-1], data[:, -1]

# Графік вхідних даних
# Тут видно, що одного класу значно більше, ніж іншого
plt.scatter(X[:, 0], X[:, 1], c=y, edgecolors='black', s=40)
plt.title("Вхідні дані з дисбалансом класів")
plt.xlabel("X1")
plt.ylabel("X2")
plt.show()

# Розбиваємо дані на навчальну і тестову вибірки
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=5
)

# Модель без урахування дисбалансу
# Вона може ігнорувати менший клас, бо більший клас переважає
classifier = ExtraTreesClassifier(
    n_estimators=100,
    max_depth=4,
    random_state=0
)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print("Без урахування дисбалансу:")
print(classification_report(y_test, y_pred, zero_division=0))

# Графік меж класифікатора без балансування
visualize_classifier(
    classifier,
    X_test,
    y_test,
    "Класифікатор без урахування дисбалансу"
)

# Модель з урахуванням дисбалансу
# class_weight='balanced' дає більшу вагу меншому класу
classifier_balanced = ExtraTreesClassifier(
    n_estimators=100,
    max_depth=4,
    random_state=0,
    class_weight='balanced'
)

classifier_balanced.fit(X_train, y_train)
y_pred_balanced = classifier_balanced.predict(X_test)

print("З урахуванням дисбалансу:")
print(classification_report(y_test, y_pred_balanced, zero_division=0))

# Графік меж класифікатора з балансуванням
visualize_classifier(
    classifier_balanced,
    X_test,
    y_test,
    "Класифікатор з урахуванням дисбалансу"
)