# -*- coding: utf-8 -*-
"""LR_5_task5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kth8e3jlXQCotOEEmqi2FH5RyOpD49Zp
"""

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error

# Завантаження даних з файлу
# Дані: день, час, команда, матч (yes/no), кількість авто
input_file = 'traffic_data.txt'

data = []
with open(input_file, 'r') as f:
    for line in f.readlines():
        items = line.strip().split(',')
        data.append(items)

data = np.array(data)

# Кодування нечислових ознак
# Перетворюємо текст у числа (бо модель працює тільки з числами)
label_encoders = []
X_encoded = np.empty(data.shape)

for i, item in enumerate(data[0]):
    if item.isdigit():
        X_encoded[:, i] = data[:, i]
    else:
        le = LabelEncoder()
        X_encoded[:, i] = le.fit_transform(data[:, i])
        label_encoders.append(le)

# Розділення на X і y
# Остання колонка — це ціль (кількість машин)
X = X_encoded[:, :-1].astype(float)
y = X_encoded[:, -1].astype(float)

# Розбиття на train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=5
)

# Створення моделі
regressor = ExtraTreesRegressor(
    n_estimators=100,
    max_depth=4,
    random_state=0
)

# Навчання
regressor.fit(X_train, y_train)

# Прогноз
y_pred = regressor.predict(X_test)

# Оцінка
print("Mean absolute error =", round(mean_absolute_error(y_test, y_pred), 2))

# --- Тестова точка ---
# Перевіряємо модель на нових даних
test_datapoint = ['Saturday', '10:20', 'Atlanta', 'no']

test_encoded = [-1] * len(test_datapoint)
count = 0

for i, item in enumerate(test_datapoint):
    if item.isdigit():
        test_encoded[i] = int(item)
    else:
        test_encoded[i] = label_encoders[count].transform([item])[0]
        count += 1

test_encoded = np.array(test_encoded).reshape(1, -1)

# Прогноз для нової точки
prediction = regressor.predict(test_encoded)

print("Прогноз кількості машин:", int(prediction[0]))