# -*- coding: utf-8 -*-
"""LR_5_task_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kth8e3jlXQCotOEEmqi2FH5RyOpD49Zp
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Завантаження даних з файлу
# Перші дві колонки — це ознаки, остання колонка — клас
input_file = 'data_imbalance.txt'
data = np.loadtxt(input_file, delimiter=',')

# Розділяємо дані на X та y
X, y = data[:, :-1], data[:, -1]

# Візуалізація вхідних даних
# Тут видно, що одного класу значно більше, ніж іншого
plt.scatter(X[:, 0], X[:, 1], c=y)
plt.title("Вхідні дані з дисбалансом класів")
plt.xlabel("X1")
plt.ylabel("X2")
plt.show()

# Розбиваємо дані на навчальну і тестову вибірки
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=5
)

# Модель без урахування дисбалансу класів
# У цьому випадку класифікатор може більше орієнтуватися на клас,
# якого у даних більше
classifier = ExtraTreesClassifier(
    n_estimators=100,
    max_depth=4,
    random_state=0
)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print("Без урахування дисбалансу:")
print(classification_report(y_test, y_pred, zero_division=0))

# Модель з урахуванням дисбалансу класів
# class_weight='balanced' змушує модель враховувати,
# що одного класу менше, і не ігнорувати його
classifier_balanced = ExtraTreesClassifier(
    n_estimators=100,
    max_depth=4,
    random_state=0,
    class_weight='balanced'
)

classifier_balanced.fit(X_train, y_train)
y_pred_balanced = classifier_balanced.predict(X_test)

print("З урахуванням дисбалансу:")
print(classification_report(y_test, y_pred_balanced, zero_division=0))