# -*- coding: utf-8 -*-
"""LR_5_task_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kth8e3jlXQCotOEEmqi2FH5RyOpD49Zp
"""

import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import classification_report

# Завантаження даних
# Перші 2 колонки — ознаки, остання — клас
input_file = 'data_random_forests.txt'
data = np.loadtxt(input_file, delimiter=',')

X, y = data[:, :-1], data[:, -1]

# Розбиття на навчальні і тестові дані
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=5
)

# Сітка параметрів для підбору
# n_estimators — кількість дерев
# max_depth — глибина дерев
param_grid = {
    'n_estimators': [25, 50, 100, 250],
    'max_depth': [2, 4, 7, 12]
}

# Метрики, які будемо оптимізувати
metrics = ['precision_weighted', 'recall_weighted']

for metric in metrics:
    print("\nПошук параметрів для:", metric)

    # Створення Grid Search
    grid = GridSearchCV(
        ExtraTreesClassifier(random_state=0),
        param_grid,
        cv=5,
        scoring=metric
    )

    # Навчання
    grid.fit(X_train, y_train)

    # Найкращі параметри
    print("Найкращі параметри:", grid.best_params_)

    # Прогноз на тесті
    y_pred = grid.predict(X_test)

    # Вивід результатів
    print("Результати класифікації:")
    print(classification_report(y_test, y_pred))