# -*- coding: utf-8 -*-
"""LR_5_task_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kth8e3jlXQCotOEEmqi2FH5RyOpD49Zp
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, explained_variance_score
from sklearn.utils import shuffle

# Завантаження даних (замість Boston)
housing_data = fetch_california_housing()

# Перемішування даних
X, y = shuffle(housing_data.data, housing_data.target, random_state=7)

# Розбиття на train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=7
)

# Модель AdaBoost
regressor = AdaBoostRegressor(
    DecisionTreeRegressor(max_depth=4),
    n_estimators=400,
    random_state=7
)

# Навчання
regressor.fit(X_train, y_train)

# Прогноз
y_pred = regressor.predict(X_test)

# Метрики
print("ADABOOST REGRESSOR")
print("Mean squared error =", round(mean_squared_error(y_test, y_pred), 2))
print("Explained variance score =", round(explained_variance_score(y_test, y_pred), 2))

# Важливість ознак
feature_importances = regressor.feature_importances_

# Нормалізація
feature_importances = 100.0 * (feature_importances / max(feature_importances))

# Сортування
index_sorted = np.flipud(np.argsort(feature_importances))

# Позиції
pos = np.arange(index_sorted.shape[0]) + 0.5

# Графік
plt.figure()
plt.bar(pos, feature_importances[index_sorted], align='center')
plt.xticks(pos, np.array(housing_data.feature_names)[index_sorted], rotation=45)
plt.ylabel('Relative Importance')
plt.title('Важливість ознак (AdaBoost)')
plt.tight_layout()
plt.show()