# -*- coding: utf-8 -*-
"""LR_5_task_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kth8e3jlXQCotOEEmqi2FH5RyOpD49Zp
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Завантаження даних
input_file = 'data_random_forests.txt'
data = np.loadtxt(input_file, delimiter=',')

X, y = data[:, :-1], data[:, -1]

# Візуалізація даних
plt.scatter(X[:, 0], X[:, 1], c=y)
plt.title("Вхідні дані")
plt.show()

# Розбиття
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=5)

# Random Forest
rf = RandomForestClassifier(n_estimators=100, max_depth=4, random_state=0)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print("Random Forest:")
print(classification_report(y_test, y_pred_rf))

# Extra Trees
erf = ExtraTreesClassifier(n_estimators=100, max_depth=4, random_state=0)
erf.fit(X_train, y_train)
y_pred_erf = erf.predict(X_test)

print("Extra Trees:")
print(classification_report(y_test, y_pred_erf))