# -*- coding: utf-8 -*-
"""LR_6_task_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuhjGInv8hs9X3L8yUPJXnBEtiqy6YTg
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

# Завантаження даних
url = "https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv"
data = pd.read_csv(url)

# Видаляємо пропущені значення
data = data.dropna()

# Перетворення категоріальних даних у числа
label_encoders = {}
for column in data.columns:
    if data[column].dtype == 'object':
        le = LabelEncoder()
        data[column] = le.fit_transform(data[column])
        label_encoders[column] = le

# Вибираємо цільову змінну (price)
X = data.drop('median_house_value', axis=1)
y = data['median_house_value']

# Перетворимо price у категорії (дешево/дорого)
y = pd.cut(y, bins=3, labels=[0, 1, 2])

# Розбиття даних
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Створення моделі
model = GaussianNB()

# Навчання
model.fit(X_train, y_train)

# Прогноз
y_pred = model.predict(X_test)

# Оцінка
print("Accuracy:", round(accuracy_score(y_test, y_pred), 2))
print(classification_report(y_test, y_pred))