# -*- coding: utf-8 -*-
"""LR_6_task_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuhjGInv8hs9X3L8yUPJXnBEtiqy6YTg
"""

# Ймовірності
P_yes = (4/9) * (3/9) * (6/9) * (9/14)
P_no = (0/5) * (4/5) * (2/5) * (5/14)

# Нормалізація
total = P_yes + P_no

P_yes_final = P_yes / total if total != 0 else 0
P_no_final = P_no / total if total != 0 else 0

print("P(Yes) =", round(P_yes_final, 3))
print("P(No) =", round(P_no_final, 3))

if P_yes_final > P_no_final:
    print("Матч відбудеться")
else:
    print("Матч не відбудеться")